version: '3.8'

services:
  redis:
    image: "redis:alpine"
    container_name: redis
    volumes:
      - ./bin/redis/data:/var/lib/redis
      - ./bin/redis/conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "wallet"
    volumes:
      - ./bin/postgres:/var/lib/postgresql/data